version: '3'

services:
  db:
    image: bitnami/mongodb:4.4
    volumes:
      - mongodb_data:/bitnami/mongodb
    # ports:
    #   - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: todos

volumes:
  mongodb_data:
    driver: local
